### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sprxll** [MOMIN5/gondal.club-1.0.5-Cleaned#3]
hello, so ... I was thinking about a project in a dupe plugin, I can invest some money for this, please return in my email, kauahmsilva@gmail.com

**Comment by MOMIN5** [comment]
about that dupe plugin, im not experienced in spigot plugin making, so im not the best guy to hit up, maybe you should search for someone on https://www.mc-market.org/ they probably will help you if you intent to pay @byxgy
